apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamina-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamina-flask
  template:
    metadata:
      labels:
        app: lamina-flask
    spec:
      containers:
        - name: lamina-flask
          image: ghcr.io/usergaia/lamina-flask:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
